### PR TITLE
Add handy script for uploading file to bucket

### PR DESCRIPTION
**Pull request by NickGrantX**
# Checklist
Reminder: If any change made to this repo affects the acceptance tests then the version pin in the Pipfile in [census-rm-acceptance-tests]() needs to be updated.
* [ ] Updated census-rm-acceptance-tests version pin (if applicable)

# Motivation and Context
It'd be handy if we could upload files to buckets, directly from the pod.

# What has changed
Added a script.

# How to test?
Try it.

# Links
Trello: https://trello.com/c/YK5PSCWE

### CODE REVIEW

**Comment by NickGrantX** [comment]
[Script to upload a file to a bucket](https://trello.com/c/YK5PSCWE/1793-script-to-upload-a-file-to-a-bucket)

**Review by hbrace — COMMENTED** [review]
I think it would be helpful to have a little note in the readme detailing how to use this

**Review by hbrace — APPROVED** [review]
Tried in my env and it worked, doesn't work with all buckets as the toolbox account doesn't have permissions for some of the buckets but thats not a bad thing.

**Review by liamtoozer — APPROVED** [review]
Works great for me 👍

**Pull request merged**
