### PR TITLE
Add Exception Manager to Toolbox

### PR DESCRIPTION
**Pull request by NickGrantX**
# Motivation and Context
To be able to skip messages on Rabbit without any downtime, we need the Exception Manager.

# What has changed
Added commands to be able to list bad messages, view errors, peek at message contents, skip messages and view skipped message history.

# How to test?
Load it all into a test environment and try it.

# Links
[Trello](https://trello.com/c/f7LmzvJm)

### CODE REVIEW

**Comment by NickGrantX** [comment]
[SPIKE: zero downtime message quarantine and error log reduction (5 days)](https://trello.com/c/f7LmzvJm/1244-spike-zero-downtime-message-quarantine-and-error-log-reduction-5-days)

**Comment by NickGrantX** [comment]
[Exception Manager v1.0](https://trello.com/c/2rkYNAMa/1266-exception-manager-v10)

**Comment by rjweeks** [comment]
Should we put a circuit breaker on this? https://microservices.io/patterns/reliability/circuit-breaker.html

**Review by liamtoozer — APPROVED** [review]
LGTM 👍

**Review by AdamHawtin — APPROVED** [review]

**Pull request merged**
